[package]
name = "metrics_cloudwatch"
version = "0.4.0"
authors = ["ramn <github@rymdimperiet.org>"]
edition = "2018"

description = "CloudWatch emitter for the metrics crate"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/metrics_cloudwatch"
homepage = "https://github.com/ramn/metrics_cloudwatch"
repository = "https://github.com/ramn/metrics_cloudwatch"
readme = "README.md"
keywords = ["metrics", "cloudwatch", "aws"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"
futures = "0.3.4"
log = "0.4.8"
metrics = { version = "0.12.1", features = ["std"] }
rusoto_cloudwatch = "0.43.0"
rusoto_core = "0.43.0"
stream-cancel = "0.5.2"
tokio = { version = "0.2.13", features = ["full"] }

[dev-dependencies]
async-trait = "0.1.24"
tokio = { version = "0.2.13", features = ["full", "test-util"] }
