[package]
name = "metrics_cloudwatch"
version = "0.1.1"
authors = ["ramn <github@rymdimperiet.org>"]
edition = "2018"

description = "CloudWatch emitter for the metrics crate"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/metrics_cloudwatch"
homepage = "https://github.com/ramn/metrics_cloudwatch"
repository = "https://github.com/ramn/metrics_cloudwatch"
readme = "README.md"
keywords = ["metrics", "cloudwatch", "aws"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
futures = { version = "0.3.4", features = ["compat"] }
log = "0.4.8"
metrics = { version = "0.12.1", features = ["std"] }
rusoto_cloudwatch = "0.42.0"
rusoto_core = "0.42.0"
tokio = { version = "0.2.11", features = ["full"] }
